version: '2'

services:
  app:
    image: 'starthub:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/starthub
      - SERVER_PORT= 8181

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
#  pgadmin-data:

